sudo: false
language: rust

rust:
  - nightly
  - beta
  - stable
  - 1.6.0

before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
  - |
    travis-cargo --skip 1.6.0 build &&
    travis-cargo --skip 1.6.0 test &&
    travis-cargo build -- --features=no_std &&
    travis-cargo test -- --features=no_std

after_success:
  - |
    if [ "$TRAVIS_RUST_VERSION" == "stable ]; then
        travis-cargo doc -- --features=no_std &&
        mv target/doc target/doc_no_std &&
        travis-cargo doc &&
        mv target/doc_no_std target/doc/no_std &&
        travis-cargo doc-upload
    fi

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="" # no unstable feature
    - secure: ddcWXicVcCooC+Dy8guGruZY2bAU3oyGjrxdC3YNfBYdatEKzW1toAiQyN8SRyZyfoHsbb7lh4YeBfv1rpmTPM6nvHMz9CHMlvED8Y+/QuYoKN2qrNiQ7eQ9xSVhOVlha/GMPSZXxmEIuJVj0Dn1D/S4RWyNMKCJdj2YvybPzOU=
