sudo: false
language: rust

script:
  - cargo test
  - cargo doc
after_success: |
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  echo '<meta http-equiv=refresh content=0;url=ascii/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  ~/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages