[package]

name = "ascii"
version = "0.3.0"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]

description = "`Ascii` type and related functionality, previously in `std::ascii`."
license = "Apache-2.0 / MIT"
repository = "https://github.com/SimonSapin/rust-ascii"
